swagger: "2.0"
info:
  version: 1.0.0
  title: A RESTful Adventure
host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /characters:
    get:
      summary: List all Characters
      operationId: list_characters
      responses:
        200:
          description: An array of Characters
          schema:
            $ref: "#/definitions/Characters"
          examples:
            application/json: |-
              {
                "characters": [
                  {
                    "id": "1234",
                    "name": "Knox Thunderbane",
                    "dungeon_id": "2345",
                    "room_id": "3456"
                  }
                ]
              }
    post:
      summary: Create a Character
      operationId: create_character
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 256
      x-examples:
        application/json: { "name": "Knox Thunderbane" }
      responses:
        201:
          description: Character created
          headers:
            Location:
              type: string
              format: url
              description: A link to the Character
          schema:
            $ref: "#/definitions/Character"
          examples:
            application/json: |-
              {
                "id": "1234",
                "name": "Knox Thunderbane"
              }
        default:
          description: Unexpected errors
          schema:
            $ref: "#/definitions/Error"
  /characters/{character_id}:
    get:
      summary: Get a specific Character
      operationId: get_character
      parameters:
        - name: character_id
          in: path
          required: true
          type: string
          description: The id of the Character to retrieve
      responses:
        200:
          description: A Character
          schema:
            $ref: "#/definitions/Character"
          examples:
            application/json: |-
              {
                "id": "1234",
                "name": "Knox Thunderbane",
                "dungeon_id": "2345",
                "room_id": "3456"
              }
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/Error"
    put:
      summary: Update a Character
      operationId: update_character
      parameters:
        - name: character_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          description: Rename a Character or move them to a new room.
          schema:
            $ref: "#/definitions/Character"
      x-examples:
        application/json: |-
          {
            "id": "1234",
            "name": "Knox Thunderbane",
            "dungeon_id": "2345",
            "room_id": "4567"
          }
      responses:
        204:
          description: Character updated
        default:
          description: Unexpected errors
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete a Character
      operationId: delete_character
      parameters:
        - name: character_id
          in: path
          required: true
          type: string
          description: The id of the Character to delete
      responses:
        204:
          description: Character deleted
        default:
          description: Unexpected errors
          schema:
            $ref: "#/definitions/Error"
  /dungeons:
    get:
      summary: List all Dungeons
      operationId: list_dungeons
      responses:
        200:
          description: An array of Dungeons
          schema:
            $ref: "#/definitions/Dungeons"
          examples:
            application/json: |-
              {
                "dungeons": [
                  {
                    "id": "1234",
                    "name": "Dungeon of Doom",
                    "entrance_room_id": "1000"
                  },
                  {
                    "id": "9876",
                    "name": "Dungeon of Hope",
                    "entrance_room_id": "2000"
                  }
                ]
              }
  /dungeons/{dungeon_id}:
    get:
      summary: Get a specific Dungeon
      operationId: get_dungeon
      parameters:
        - name: dungeon_id
          in: path
          required: true
          description: The id of the Dungeon to retrieve
          type: string
      responses:
        200:
          description: A Dungeon
          schema:
            $ref: "#/definitions/Dungeon"
          examples:
            application/json: |-
              {
                "id": "1234",
                "name": "Dungeon of Doom",
                "entrance_room_id": "1000"
              }
        default:
          description: Unexpected errors
          schema:
            $ref: "#/definitions/Error"
  /dungeons/{dungeon_id}/rooms/{room_id}:
    get:
      summary: Get a specific Room in a specific Dungeon
      operationId: get_room
      parameters:
        - name: dungeon_id
          in: path
          description: The id of the Dungeon
          required: true
          type: string
        - name: room_id
          in: path
          description: The id of the Room
          required: true
          type: string
      responses:
        200:
          description: Expected response to a valid request
          schema:
            $ref: "#/definitions/Room"
          examples:
            application/json: |-
              {
                "id": "1000",
                "name": "Entrance",
                "dungeon_id": "1234",
                "is_exit": false,
                "doors": [
                  {
                    "room_id": "1001",
                    "direction": "east"
                  }
                ]
              }
        400:
          description: You tried to teleport. That's just not allowed.
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json: |-
              {
                "transaction_id": "71607e7c-df7c-45f3-b571-d1829de4ad9a",
                "code": "736.9",
                "title": "Teleport Denied",
                "description": "The room you tried to visit does not exist or is not accessible from your current room. Thought you could get away with it didn't you.",
                "link": {
                    "rel": "help",
                    "href": "http://en.wikipedia.org/wiki/No-teleportation_theorem"
                  }
              }
        default:
          description: Unexpected errors
          schema:
            $ref: "#/definitions/Error"
definitions:
  Character:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
        maxLength: 256
      dungeon_id:
        type: string
      room_id:
        type: string
  Characters:
    type: object
    readOnly: true
    properties:
      characters:
        type: array
        items:
          $ref: "#/definitions/Character"
  Room:
    type: object
    readOnly: true
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
      dungeon_id:
        type: string
      is_exit:
        type: boolean
      doors:
        type: array
        items:
          type: object
          properties:
            room_id:
              type: string
            direction:
              type: string
              enum:
                - north
                - south
                - east
                - west
  Dungeon:
    type: object
    readOnly: true
    properties:
      id:
        type: string
      entrance_room_id:
        type: string
      name:
        type: string
  Dungeons:
    type: object
    readOnly: true
    properties:
      dungeons:
        type: array
        items:
          $ref: "#/definitions/Dungeon"
  Error:
    type: object
    readOnly: true
    properties:
      transaction_id:
        type: string
        description: A transaction id for error response. Used to easily match an API user debugging their application to the errors on the server side, as discoverable by the operations team running the API.
      code:
        type: string
        description: A machine readable application error code. Not to be confused with the HTTP status code in the response.
      title:
        type: string
        description: A short, human readable title of the error.
      description:
        type: string
        description: A long, human readable description of the error.
      link:
        properties:
          rel:
            type: string
            enum: [ "help" ]
          href:
            type: string
            format: url
            description: A link to a document containing more information about the error and how to take action on it.
